# Generated by Django 6.0.4 on 2026-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveaxlemodel',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='enginemodel',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='failurenode',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='steeraxlemodel',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='transmissionmodel',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='directory_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='Название справочника'),
        ),
    ]
